# Generated by Django 6.1.1 on 2026-09-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('is_completed', models.BooleanField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=1000)),
            ],
            options={
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='GameSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=1000)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.games')),
                ('platforms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.platforms')),
            ],
            options={
                'db_table': 'game_sources',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
                ('game_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gamesources')),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_unlocked', models.DateTimeField()),
                ('achievements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.achievements')),
            ],
            options={
                'db_table': 'user_achievements',
            },
        ),
    ]
