# Generated by Django 6.1.1 on 2026-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='game_source_id',
            new_name='game_source',
        ),
        migrations.RenameField(
            model_name='gamesources',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamesources',
            old_name='platforms_id',
            new_name='platforms',
        ),
        migrations.RenameField(
            model_name='userachievements',
            old_name='achievements_id',
            new_name='achievements',
        ),
    ]
