# Generated by Django 6.1.1 on 2026-09-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_game_source_id_achievements_game_source_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='GameSources',
            new_name='GameSource',
        ),
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
        migrations.RenameModel(
            old_name='UserAchievements',
            new_name='UserAchievement',
        ),
    ]
